@startuml Containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "Пользователь системы")

System_Ext(device, "Подключаемое устройство", "IoT устройство (ворота, термостат)")

Container(apiGateway, "ApiGateway", "Маршрутизация запросов к соответствующим сервисам")

System_Boundary(userDomain, "Пользователи и дома") {
    Container(userService, "UserService", "Управление пользователями и домами")
    ContainerDb(userDb, "UserDB", "PostgreSQL", "Хранение данных пользователей и домов")
}

System_Boundary(automationDomain, "Автоматизация") {
    Container(automationService, "AutomationService", "Управление автоматизацией и сценариями")
    ContainerDb(automationDb, "AutomationDB", "PostgreSQL", "Хранение данных сценариев автоматизации")
}

System_Boundary(deviceDomain, "Устройства") {
    Container(deviceService, "DeviceService", "Управление устройствами, отправка команд, получение данных")    
    ContainerDb(deviceDb, "DeviceDB", "PostgreSQL", "Хранение данных устройств")    
}

System_Boundary(telemetryDomain, "Телеметрия") {
    Container(telemetryService, "TelemetryService", "Сбор и обработка данных от устройств")
    ContainerDb(telemetryDb, "TelemetryDB", "Time series DB", "Хранение телеметрии от устройств")
}

ContainerQueue(deviceQueue, "MQTT", "Брокер сообщений для обмена данными с устройствами")

Rel_Down(user, apiGateway, "Использует")
Rel_Right(user, device, "Взаимодействует с")

Rel(apiGateway, userService, "Управляет пользователями и домами")
Rel(apiGateway, automationService, "Настраивает автоматизацию")
Rel(apiGateway, deviceService, "Управляет устройствами")
Rel(apiGateway, telemetryService, "Получает данные от устройств")

Rel(userService, userDb, "Читает и записывает")
Rel(deviceService, deviceDb, "Читает и записывает")
Rel(automationService, automationDb, "Читает и записывает")
Rel(telemetryService, telemetryDb, "Читает и записывает")

Rel(automationService, deviceService, "Отправляет команды")
Rel(deviceService, deviceQueue, "Публикует команды и получает данные")
Rel(telemetryService, deviceQueue, "Подписывается на данные от устройств")

Rel(device, deviceQueue, "Отправляет данные и получает команды")

@enduml