@startuml UserService
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component_Ext(gateway, "ApiGateway", "Маршрутизация запросов к соответствующим сервисам")
ComponentDb(userDb, "UserDB", "PostgreSQL", "Хранение данных пользователей и домов")

Container_Boundary(userService, "UserService", "Управление пользователями и домами") {
    Component(authController, "AuthController", "REST API для аутентификации и управления сессиями")
    Component(usersController, "UsersController", "REST API для управления пользователями (CRUD)")
    Component(homesController, "HomesController", "REST API для управления домами и устройствами в домах (CRUD)")

    Component(authService, "AuthService", "Аутентификация, управление сессиями")
    Component(usersService, "UsersService", "Бизнес-логика управления пользователями")
    Component(homesService, "HomesService", "Бизнес-логика управления домами и устройствами в домах")
        
    Component(authRepository, "AuthRepository", "Доступ к данным аутентификации и сессий")
    Component(usersRepository, "UsersRepository", "Доступ к данным пользователей")
    Component(homesRepository, "HomesRepository", "Доступ к данным домов и устройств в домах")
    Rel(authController, authService, "Использует")
    Rel(usersController, usersService, "Использует")
    Rel(homesController, homesService, "Использует")

    Rel(authService, authRepository, "Взаимодействует с данными через")
    Rel(usersService, usersRepository, "Взаимодействует с данными через")
    Rel(homesService, homesRepository, "Взаимодействует с данными через")

    Rel(authRepository, userDb, "Читает и записывает данные")
    Rel(usersRepository, userDb, "Читает и записывает данные")
    Rel(homesRepository, userDb, "Читает и записывает данные")
}

Rel(gateway, authController, "Обращается к")
Rel(gateway, usersController, "Обращается к")
Rel(gateway, homesController, "Обращается к")

@enduml